/*
 * WASM OJ Wonderland API
 *
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Auth200Response {
    /// Whether the token is valid
    #[serde(rename = "ok")]
    pub ok: bool,
    /// Whether the user is new
    #[serde(rename = "new")]
    pub new: bool,
}

impl Auth200Response {
    pub fn new(ok: bool, new: bool) -> Auth200Response {
        Auth200Response {
            ok,
            new,
        }
    }
}


