/*
 * WASM OJ Wonderland API
 *
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetProblem200Response {
    #[serde(rename = "problem")]
    pub problem: Box<crate::models::GetProblem200ResponseProblem>,
}

impl GetProblem200Response {
    pub fn new(problem: crate::models::GetProblem200ResponseProblem) -> GetProblem200Response {
        GetProblem200Response {
            problem: Box::new(problem),
        }
    }
}


