/*
 * WASM OJ Wonderland API
 *
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetProblem200ResponseProblemPolicyInner {
    #[serde(rename = "budget")]
    pub budget: f32,
    #[serde(rename = "memory")]
    pub memory: f32,
    #[serde(rename = "score")]
    pub score: f32,
}

impl GetProblem200ResponseProblemPolicyInner {
    pub fn new(budget: f32, memory: f32, score: f32) -> GetProblem200ResponseProblemPolicyInner {
        GetProblem200ResponseProblemPolicyInner {
            budget,
            memory,
            score,
        }
    }
}


