/*
 * WASM OJ Wonderland API
 *
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetProblem200ResponseProblemTestcaseInner {
    #[serde(rename = "score")]
    pub score: f32,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "sample", skip_serializing_if = "Option::is_none")]
    pub sample: Option<bool>,
    #[serde(rename = "stdin", skip_serializing_if = "Option::is_none")]
    pub stdin: Option<String>,
    #[serde(rename = "stdout", skip_serializing_if = "Option::is_none")]
    pub stdout: Option<String>,
    #[serde(rename = "stdin_file", skip_serializing_if = "Option::is_none")]
    pub stdin_file: Option<String>,
    #[serde(rename = "stdout_file", skip_serializing_if = "Option::is_none")]
    pub stdout_file: Option<String>,
}

impl GetProblem200ResponseProblemTestcaseInner {
    pub fn new(score: f32) -> GetProblem200ResponseProblemTestcaseInner {
        GetProblem200ResponseProblemTestcaseInner {
            score,
            description: None,
            sample: None,
            stdin: None,
            stdout: None,
            stdin_file: None,
            stdout_file: None,
        }
    }
}


