/*
 * WASM OJ Wonderland API
 *
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSubmission200Response {
    #[serde(rename = "submission")]
    pub submission: Box<crate::models::GetSubmission200ResponseSubmission>,
    #[serde(rename = "problem")]
    pub problem: Box<crate::models::GetProblem200ResponseProblem>,
}

impl GetSubmission200Response {
    pub fn new(submission: crate::models::GetSubmission200ResponseSubmission, problem: crate::models::GetProblem200ResponseProblem) -> GetSubmission200Response {
        GetSubmission200Response {
            submission: Box::new(submission),
            problem: Box::new(problem),
        }
    }
}


