/*
 * WASM OJ Wonderland API
 *
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Login200Response {
    /// Whether the email was sent successfully, always true
    #[serde(rename = "ok")]
    pub ok: bool,
    /// Time when the email was sent
    #[serde(rename = "send")]
    pub send: String,
}

impl Login200Response {
    pub fn new(ok: bool, send: String) -> Login200Response {
        Login200Response {
            ok,
            send,
        }
    }
}


