/*
 * WASM OJ Wonderland API
 *
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LoginRequest {
    /// User's email address
    #[serde(rename = "email")]
    pub email: String,
    /// Token's time to live in days
    #[serde(rename = "ttl")]
    pub ttl: i32,
    /// Whether the token is for device login
    #[serde(rename = "device")]
    pub device: bool,
}

impl LoginRequest {
    pub fn new(email: String, ttl: i32, device: bool) -> LoginRequest {
        LoginRequest {
            email,
            ttl,
            device,
        }
    }
}


