/*
 * WASM OJ Wonderland API
 *
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Me200Response {
    /// User ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// User's email
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Token expiration time, in seconds since epoch
    #[serde(rename = "exp", skip_serializing_if = "Option::is_none")]
    pub exp: Option<f32>,
    /// The PEA login URL that this app uses
    #[serde(rename = "pea")]
    pub pea: String,
}

impl Me200Response {
    pub fn new(pea: String) -> Me200Response {
        Me200Response {
            id: None,
            email: None,
            exp: None,
            pea,
        }
    }
}


