/*
 * WASM OJ Wonderland API
 *
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Submit200Response {
    /// Submission ID
    #[serde(rename = "submission_id")]
    pub submission_id: String,
}

impl Submit200Response {
    pub fn new(submission_id: String) -> Submit200Response {
        Submit200Response {
            submission_id,
        }
    }
}


