/*
 * WASM OJ Wonderland API
 *
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct System200Response {
    #[serde(rename = "cfg")]
    pub cfg: Box<crate::models::System200ResponseCfg>,
    #[serde(rename = "stat")]
    pub stat: Box<crate::models::System200ResponseStat>,
}

impl System200Response {
    pub fn new(cfg: crate::models::System200ResponseCfg, stat: crate::models::System200ResponseStat) -> System200Response {
        System200Response {
            cfg: Box::new(cfg),
            stat: Box::new(stat),
        }
    }
}


