/*
 * WASM OJ Wonderland API
 *
 * You can interact with WASM OJ Wonderland through this API
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: jacob@csie.cool
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct System200ResponseCfg {
    /// Number of compilers configured
    #[serde(rename = "compilers")]
    pub compilers: f32,
    /// Number of runners configured
    #[serde(rename = "runners")]
    pub runners: f32,
}

impl System200ResponseCfg {
    pub fn new(compilers: f32, runners: f32) -> System200ResponseCfg {
        System200ResponseCfg {
            compilers,
            runners,
        }
    }
}


